# ── Per-model import map ────────────────────────────────────────────────────
_MODEL_IMPORT = {
    "logistic_regression": "from sklearn.linear_model import LogisticRegression",
    "knn":                 "from sklearn.neighbors import KNeighborsClassifier",
    "decision_tree":       "from sklearn.tree import DecisionTreeClassifier",
    "random_forest":       "from sklearn.ensemble import RandomForestClassifier",
    "gradient_boosting":   "from sklearn.ensemble import GradientBoostingClassifier",
    "svm":                 "from sklearn.svm import SVC",
    "naive_bayes":         "from sklearn.naive_bayes import GaussianNB",
    "lda":                 "from sklearn.discriminant_analysis import LinearDiscriminantAnalysis",
    "adaboost":            "from sklearn.ensemble import AdaBoostClassifier",
    "voting":              "from sklearn.ensemble import VotingClassifier",
}

# Models that are wrapped in a StandardScaler Pipeline
_NEEDS_SCALER = {"logistic_regression", "knn", "svm", "lda", "naive_bayes"}

# ── Per-model constructor map ───────────────────────────────────────────────
def _build_constructor(model_key: str, user_params: dict) -> str:
    """Return the model constructor call as a string, e.g. 'SVC(C=1.0, kernel="rbf")'"""
    class_map = {
        "logistic_regression": "LogisticRegression",
        "knn":                 "KNeighborsClassifier",
        "decision_tree":       "DecisionTreeClassifier",
        "random_forest":       "RandomForestClassifier",
        "gradient_boosting":   "GradientBoostingClassifier",
        "svm":                 "SVC",
        "naive_bayes":         "GaussianNB",
        "lda":                 "LinearDiscriminantAnalysis",
        "adaboost":            "AdaBoostClassifier",
        "voting":              "VotingClassifier",
    }
    cls = class_map.get(model_key, "UnknownModel")

    # Format param values correctly (strings need quotes, numbers/bools don't)
    def _fmt(v):
        if isinstance(v, str):
            return f'"{v}"'
        if isinstance(v, bool):
            return str(v)
        if isinstance(v, float):
            return repr(round(v, 8))
        return repr(v)

    params_str = ", ".join(f"{k}={_fmt(v)}" for k, v in user_params.items())
    return f"{cls}({params_str})"


#---Synthetic dataset loader snippet---#
_SYNTHETIC_LOADER = {
    "moons": (
        "from sklearn.datasets import make_moons\n"
        "X, y = make_moons(n_samples={n_samples}, noise={noise}, random_state={seed})"
    ),
    "circles": (
        "from sklearn.datasets import make_circles\n"
        "X, y = make_circles(n_samples={n_samples}, noise={noise}, random_state={seed})"
    ),
    "blobs": (
        "from sklearn.datasets import make_blobs\n"
        "X, y = make_blobs(n_samples={n_samples}, random_state={seed})"
    ),
    "linear": (
        "from sklearn.datasets import make_classification\n"
        "X, y = make_classification(n_samples={n_samples}, n_features=2, "
        "n_redundant=0, random_state={seed})"
    ),
    "xor": (
        "import numpy as np\n"
        "rng = np.random.RandomState({seed})\n"
        "X = rng.randn({n_samples}, 2)\n"
        "y = np.array(X[:, 0] * X[:, 1] > 0, dtype=int)"
    ),
}

_REAL_LOADER = {
    "iris":          "from sklearn.datasets import load_iris\ndata = load_iris()\nX, y = data.data, data.target",
    "wine":          "from sklearn.datasets import load_wine\ndata = load_wine()\nX, y = data.data, data.target",
    "breast_cancer": "from sklearn.datasets import load_breast_cancer\ndata = load_breast_cancer()\nX, y = data.data, data.target",
}


def generate_export_code(
    model_key: str,
    user_params: dict,
    dataset_source: str,       # "Synthetic" | "Real (sklearn)"
    dataset_key: str,
    n_samples: int = 300,
    noise: float = 0.1,
    random_seed: int = 42,
    test_split: float = 0.2,
) -> str:
    """
    Build and return a complete, runnable Python script string.
    """
    needs_scaler = model_key in _NEEDS_SCALER
    constructor  = _build_constructor(model_key, user_params)
    model_import = _MODEL_IMPORT.get(model_key, "# unknown model")

    # ── 1. Header
    lines = [
        "# ════════════════════════════════════════════════════════════",
        "# Auto-generated by ML Playground",
        "# Reproduces the exact dataset + model + hyperparameters",
        "# you configured in the app.",
        "# ════════════════════════════════════════════════════════════",
        "",
    ]

    # ── 2. Imports
    lines += [
        "# ── Imports",
        "import numpy as np",
        "from sklearn.model_selection import train_test_split",
        "from sklearn.metrics import accuracy_score, f1_score, classification_report",
    ]
    if needs_scaler:
        lines += [
            "from sklearn.preprocessing import StandardScaler",
            "from sklearn.pipeline import Pipeline",
        ]
    lines += [model_import, ""]

    # ── 3. Dataset
    lines += ["# ── Dataset"]
    if dataset_source == "Synthetic":
        template = _SYNTHETIC_LOADER.get(
            dataset_key,
            "from sklearn.datasets import make_classification\nX, y = make_classification(n_samples={n_samples}, random_state={seed})"
        )
        lines.append(
            template.format(n_samples=n_samples, noise=noise, seed=random_seed)
        )
    else:
        loader = _REAL_LOADER.get(
            dataset_key,
            "from sklearn.datasets import load_iris\ndata = load_iris()\nX, y = data.data, data.target  # fallback"
        )
        lines.append(loader)
    lines.append("")

    # ── 4. Train / test split
    lines += [
        "# ── Train / test split",
        f"X_train, X_test, y_train, y_test = train_test_split(",
        f"    X, y,",
        f"    test_size={test_split},",
        f"    random_state={random_seed},",
        f"    stratify=y,",
        f")",
        "",
    ]

    # ── 5. Model
    lines += ["# ── Model"]
    if needs_scaler:
        lines += [
            f"# {constructor} is wrapped in a Pipeline with StandardScaler",
            f"# because this model is sensitive to feature scale.",
            f"clf = Pipeline([",
            f'    ("scaler", StandardScaler()),',
            f'    ("clf", {constructor}),',
            f"])",
        ]
    else:
        lines += [
            f"clf = {constructor}",
        ]
    lines.append("")

    # ── 6. Training
    lines += [
        "# ── Training",
        "clf.fit(X_train, y_train)",
        "",
    ]

    # ── 7. Evaluation
    lines += [
        "# ── Evaluation",
        "y_pred = clf.predict(X_test)",
        "",
        "print(f'Train accuracy : {clf.score(X_train, y_train):.4f}')",
        "print(f'Test  accuracy : {accuracy_score(y_test, y_pred):.4f}')",
        "print(f'Test  F1 score : {f1_score(y_test, y_pred, average=\"weighted\"):.4f}')",
        "print()",
        "print('Classification Report:')",
        "print(classification_report(y_test, y_pred))",
        "",
    ]

    # ── 8. Optional: predict_proba note
    proba_models = {"logistic_regression", "knn", "random_forest",
                    "gradient_boosting", "naive_bayes", "adaboost", "voting"}
    if model_key in proba_models:
        lines += [
            "# ── Probability scores (optional)",
            "# y_proba = clf.predict_proba(X_test)",
            "# Each column corresponds to a class in clf.classes_",
            "",
        ]

    return "\n".join(lines)